/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnInventorRouteImport } from './routes/learn.inventor'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AdminInventorRouteImport } from './routes/admin.inventor'
import { Route as LearnInventorIndexRouteImport } from './routes/learn.inventor.index'
import { Route as AdminTutorialsIndexRouteImport } from './routes/admin.tutorials.index'
import { Route as AdminPracticeIndexRouteImport } from './routes/admin.practice.index'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin.articles.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LearnInventorTutorialsRouteImport } from './routes/learn.inventor.tutorials'
import { Route as LearnInventorPart1RouteImport } from './routes/learn.inventor.part1'
import { Route as LearnInventorArticlesRouteImport } from './routes/learn.inventor.articles'
import { Route as ApiPublicFeedbackRouteImport } from './routes/api/public/feedback'
import { Route as AdminTutorialsSlugRouteImport } from './routes/admin.tutorials.$slug'
import { Route as AdminPracticeTaxonomyRouteImport } from './routes/admin.practice.taxonomy'
import { Route as AdminPracticeSlugRouteImport } from './routes/admin.practice.$slug'
import { Route as AdminArticlesSlugRouteImport } from './routes/admin.articles.$slug'
import { Route as LearnInventorTutorialsIndexRouteImport } from './routes/learn.inventor.tutorials.index'
import { Route as LearnInventorPart1IndexRouteImport } from './routes/learn.inventor.part1.index'
import { Route as LearnInventorArticlesIndexRouteImport } from './routes/learn.inventor.articles.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LearnInventorPart1TabIdRouteImport } from './routes/learn.inventor.part1.$tabId'
import { Route as LearnInventorArticlesSlugRouteImport } from './routes/learn.inventor.articles.$slug'
import { Route as LearnInventorTutorialsPracticeProblemsIndexRouteImport } from './routes/learn.inventor.tutorials.practice-problems.index'
import { Route as LearnInventorTutorialsLibraryIndexRouteImport } from './routes/learn.inventor.tutorials.library.index'
import { Route as LearnInventorPart1TabIdIndexRouteImport } from './routes/learn.inventor.part1.$tabId.index'
import { Route as LearnInventorTutorialsPracticeProblemsSlugRouteImport } from './routes/learn.inventor.tutorials.practice-problems.$slug'
import { Route as LearnInventorTutorialsLibraryTutorialSlugRouteImport } from './routes/learn.inventor.tutorials.library.$tutorialSlug'
import { Route as LearnInventorPart1TabIdButtonIdRouteImport } from './routes/learn.inventor.part1.$tabId.$buttonId'
import { Route as LearnInventorTutorialsLibraryTutorialSlugIndexRouteImport } from './routes/learn.inventor.tutorials.library.$tutorialSlug.index'
import { Route as LearnInventorTutorialsLibraryTutorialSlugModuleSlugRouteImport } from './routes/learn.inventor.tutorials.library.$tutorialSlug.$moduleSlug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnInventorRoute = LearnInventorRouteImport.update({
  id: '/learn/inventor',
  path: '/learn/inventor',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventorRoute = AdminInventorRouteImport.update({
  id: '/admin/inventor',
  path: '/admin/inventor',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnInventorIndexRoute = LearnInventorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnInventorRoute,
} as any)
const AdminTutorialsIndexRoute = AdminTutorialsIndexRouteImport.update({
  id: '/admin/tutorials/',
  path: '/admin/tutorials/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPracticeIndexRoute = AdminPracticeIndexRouteImport.update({
  id: '/admin/practice/',
  path: '/admin/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/admin/articles/',
  path: '/admin/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnInventorTutorialsRoute = LearnInventorTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => LearnInventorRoute,
} as any)
const LearnInventorPart1Route = LearnInventorPart1RouteImport.update({
  id: '/part1',
  path: '/part1',
  getParentRoute: () => LearnInventorRoute,
} as any)
const LearnInventorArticlesRoute = LearnInventorArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => LearnInventorRoute,
} as any)
const ApiPublicFeedbackRoute = ApiPublicFeedbackRouteImport.update({
  id: '/api/public/feedback',
  path: '/api/public/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTutorialsSlugRoute = AdminTutorialsSlugRouteImport.update({
  id: '/admin/tutorials/$slug',
  path: '/admin/tutorials/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPracticeTaxonomyRoute = AdminPracticeTaxonomyRouteImport.update({
  id: '/admin/practice/taxonomy',
  path: '/admin/practice/taxonomy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPracticeSlugRoute = AdminPracticeSlugRouteImport.update({
  id: '/admin/practice/$slug',
  path: '/admin/practice/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesSlugRoute = AdminArticlesSlugRouteImport.update({
  id: '/admin/articles/$slug',
  path: '/admin/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnInventorTutorialsIndexRoute =
  LearnInventorTutorialsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LearnInventorTutorialsRoute,
  } as any)
const LearnInventorPart1IndexRoute = LearnInventorPart1IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnInventorPart1Route,
} as any)
const LearnInventorArticlesIndexRoute =
  LearnInventorArticlesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LearnInventorArticlesRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LearnInventorPart1TabIdRoute = LearnInventorPart1TabIdRouteImport.update({
  id: '/$tabId',
  path: '/$tabId',
  getParentRoute: () => LearnInventorPart1Route,
} as any)
const LearnInventorArticlesSlugRoute =
  LearnInventorArticlesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => LearnInventorArticlesRoute,
  } as any)
const LearnInventorTutorialsPracticeProblemsIndexRoute =
  LearnInventorTutorialsPracticeProblemsIndexRouteImport.update({
    id: '/practice-problems/',
    path: '/practice-problems/',
    getParentRoute: () => LearnInventorTutorialsRoute,
  } as any)
const LearnInventorTutorialsLibraryIndexRoute =
  LearnInventorTutorialsLibraryIndexRouteImport.update({
    id: '/library/',
    path: '/library/',
    getParentRoute: () => LearnInventorTutorialsRoute,
  } as any)
const LearnInventorPart1TabIdIndexRoute =
  LearnInventorPart1TabIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LearnInventorPart1TabIdRoute,
  } as any)
const LearnInventorTutorialsPracticeProblemsSlugRoute =
  LearnInventorTutorialsPracticeProblemsSlugRouteImport.update({
    id: '/practice-problems/$slug',
    path: '/practice-problems/$slug',
    getParentRoute: () => LearnInventorTutorialsRoute,
  } as any)
const LearnInventorTutorialsLibraryTutorialSlugRoute =
  LearnInventorTutorialsLibraryTutorialSlugRouteImport.update({
    id: '/library/$tutorialSlug',
    path: '/library/$tutorialSlug',
    getParentRoute: () => LearnInventorTutorialsRoute,
  } as any)
const LearnInventorPart1TabIdButtonIdRoute =
  LearnInventorPart1TabIdButtonIdRouteImport.update({
    id: '/$buttonId',
    path: '/$buttonId',
    getParentRoute: () => LearnInventorPart1TabIdRoute,
  } as any)
const LearnInventorTutorialsLibraryTutorialSlugIndexRoute =
  LearnInventorTutorialsLibraryTutorialSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LearnInventorTutorialsLibraryTutorialSlugRoute,
  } as any)
const LearnInventorTutorialsLibraryTutorialSlugModuleSlugRoute =
  LearnInventorTutorialsLibraryTutorialSlugModuleSlugRouteImport.update({
    id: '/$moduleSlug',
    path: '/$moduleSlug',
    getParentRoute: () => LearnInventorTutorialsLibraryTutorialSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/inventor': typeof AdminInventorRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/learn/inventor': typeof LearnInventorRouteWithChildren
  '/admin/articles/$slug': typeof AdminArticlesSlugRoute
  '/admin/practice/$slug': typeof AdminPracticeSlugRoute
  '/admin/practice/taxonomy': typeof AdminPracticeTaxonomyRoute
  '/admin/tutorials/$slug': typeof AdminTutorialsSlugRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/learn/inventor/articles': typeof LearnInventorArticlesRouteWithChildren
  '/learn/inventor/part1': typeof LearnInventorPart1RouteWithChildren
  '/learn/inventor/tutorials': typeof LearnInventorTutorialsRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/practice/': typeof AdminPracticeIndexRoute
  '/admin/tutorials/': typeof AdminTutorialsIndexRoute
  '/learn/inventor/': typeof LearnInventorIndexRoute
  '/learn/inventor/articles/$slug': typeof LearnInventorArticlesSlugRoute
  '/learn/inventor/part1/$tabId': typeof LearnInventorPart1TabIdRouteWithChildren
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/learn/inventor/articles/': typeof LearnInventorArticlesIndexRoute
  '/learn/inventor/part1/': typeof LearnInventorPart1IndexRoute
  '/learn/inventor/tutorials/': typeof LearnInventorTutorialsIndexRoute
  '/learn/inventor/part1/$tabId/$buttonId': typeof LearnInventorPart1TabIdButtonIdRoute
  '/learn/inventor/tutorials/library/$tutorialSlug': typeof LearnInventorTutorialsLibraryTutorialSlugRouteWithChildren
  '/learn/inventor/tutorials/practice-problems/$slug': typeof LearnInventorTutorialsPracticeProblemsSlugRoute
  '/learn/inventor/part1/$tabId/': typeof LearnInventorPart1TabIdIndexRoute
  '/learn/inventor/tutorials/library/': typeof LearnInventorTutorialsLibraryIndexRoute
  '/learn/inventor/tutorials/practice-problems/': typeof LearnInventorTutorialsPracticeProblemsIndexRoute
  '/learn/inventor/tutorials/library/$tutorialSlug/$moduleSlug': typeof LearnInventorTutorialsLibraryTutorialSlugModuleSlugRoute
  '/learn/inventor/tutorials/library/$tutorialSlug/': typeof LearnInventorTutorialsLibraryTutorialSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/inventor': typeof AdminInventorRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/admin/articles/$slug': typeof AdminArticlesSlugRoute
  '/admin/practice/$slug': typeof AdminPracticeSlugRoute
  '/admin/practice/taxonomy': typeof AdminPracticeTaxonomyRoute
  '/admin/tutorials/$slug': typeof AdminTutorialsSlugRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
  '/admin/practice': typeof AdminPracticeIndexRoute
  '/admin/tutorials': typeof AdminTutorialsIndexRoute
  '/learn/inventor': typeof LearnInventorIndexRoute
  '/learn/inventor/articles/$slug': typeof LearnInventorArticlesSlugRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/learn/inventor/articles': typeof LearnInventorArticlesIndexRoute
  '/learn/inventor/part1': typeof LearnInventorPart1IndexRoute
  '/learn/inventor/tutorials': typeof LearnInventorTutorialsIndexRoute
  '/learn/inventor/part1/$tabId/$buttonId': typeof LearnInventorPart1TabIdButtonIdRoute
  '/learn/inventor/tutorials/practice-problems/$slug': typeof LearnInventorTutorialsPracticeProblemsSlugRoute
  '/learn/inventor/part1/$tabId': typeof LearnInventorPart1TabIdIndexRoute
  '/learn/inventor/tutorials/library': typeof LearnInventorTutorialsLibraryIndexRoute
  '/learn/inventor/tutorials/practice-problems': typeof LearnInventorTutorialsPracticeProblemsIndexRoute
  '/learn/inventor/tutorials/library/$tutorialSlug/$moduleSlug': typeof LearnInventorTutorialsLibraryTutorialSlugModuleSlugRoute
  '/learn/inventor/tutorials/library/$tutorialSlug': typeof LearnInventorTutorialsLibraryTutorialSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/inventor': typeof AdminInventorRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/learn/inventor': typeof LearnInventorRouteWithChildren
  '/admin/articles/$slug': typeof AdminArticlesSlugRoute
  '/admin/practice/$slug': typeof AdminPracticeSlugRoute
  '/admin/practice/taxonomy': typeof AdminPracticeTaxonomyRoute
  '/admin/tutorials/$slug': typeof AdminTutorialsSlugRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/learn/inventor/articles': typeof LearnInventorArticlesRouteWithChildren
  '/learn/inventor/part1': typeof LearnInventorPart1RouteWithChildren
  '/learn/inventor/tutorials': typeof LearnInventorTutorialsRouteWithChildren
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/practice/': typeof AdminPracticeIndexRoute
  '/admin/tutorials/': typeof AdminTutorialsIndexRoute
  '/learn/inventor/': typeof LearnInventorIndexRoute
  '/learn/inventor/articles/$slug': typeof LearnInventorArticlesSlugRoute
  '/learn/inventor/part1/$tabId': typeof LearnInventorPart1TabIdRouteWithChildren
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/learn/inventor/articles/': typeof LearnInventorArticlesIndexRoute
  '/learn/inventor/part1/': typeof LearnInventorPart1IndexRoute
  '/learn/inventor/tutorials/': typeof LearnInventorTutorialsIndexRoute
  '/learn/inventor/part1/$tabId/$buttonId': typeof LearnInventorPart1TabIdButtonIdRoute
  '/learn/inventor/tutorials/library/$tutorialSlug': typeof LearnInventorTutorialsLibraryTutorialSlugRouteWithChildren
  '/learn/inventor/tutorials/practice-problems/$slug': typeof LearnInventorTutorialsPracticeProblemsSlugRoute
  '/learn/inventor/part1/$tabId/': typeof LearnInventorPart1TabIdIndexRoute
  '/learn/inventor/tutorials/library/': typeof LearnInventorTutorialsLibraryIndexRoute
  '/learn/inventor/tutorials/practice-problems/': typeof LearnInventorTutorialsPracticeProblemsIndexRoute
  '/learn/inventor/tutorials/library/$tutorialSlug/$moduleSlug': typeof LearnInventorTutorialsLibraryTutorialSlugModuleSlugRoute
  '/learn/inventor/tutorials/library/$tutorialSlug/': typeof LearnInventorTutorialsLibraryTutorialSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/inventor'
    | '/email/unsubscribe'
    | '/learn/inventor'
    | '/admin/articles/$slug'
    | '/admin/practice/$slug'
    | '/admin/practice/taxonomy'
    | '/admin/tutorials/$slug'
    | '/api/public/feedback'
    | '/learn/inventor/articles'
    | '/learn/inventor/part1'
    | '/learn/inventor/tutorials'
    | '/lovable/email/suppression'
    | '/admin/articles/'
    | '/admin/practice/'
    | '/admin/tutorials/'
    | '/learn/inventor/'
    | '/learn/inventor/articles/$slug'
    | '/learn/inventor/part1/$tabId'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/learn/inventor/articles/'
    | '/learn/inventor/part1/'
    | '/learn/inventor/tutorials/'
    | '/learn/inventor/part1/$tabId/$buttonId'
    | '/learn/inventor/tutorials/library/$tutorialSlug'
    | '/learn/inventor/tutorials/practice-problems/$slug'
    | '/learn/inventor/part1/$tabId/'
    | '/learn/inventor/tutorials/library/'
    | '/learn/inventor/tutorials/practice-problems/'
    | '/learn/inventor/tutorials/library/$tutorialSlug/$moduleSlug'
    | '/learn/inventor/tutorials/library/$tutorialSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/inventor'
    | '/email/unsubscribe'
    | '/admin/articles/$slug'
    | '/admin/practice/$slug'
    | '/admin/practice/taxonomy'
    | '/admin/tutorials/$slug'
    | '/api/public/feedback'
    | '/lovable/email/suppression'
    | '/admin/articles'
    | '/admin/practice'
    | '/admin/tutorials'
    | '/learn/inventor'
    | '/learn/inventor/articles/$slug'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/learn/inventor/articles'
    | '/learn/inventor/part1'
    | '/learn/inventor/tutorials'
    | '/learn/inventor/part1/$tabId/$buttonId'
    | '/learn/inventor/tutorials/practice-problems/$slug'
    | '/learn/inventor/part1/$tabId'
    | '/learn/inventor/tutorials/library'
    | '/learn/inventor/tutorials/practice-problems'
    | '/learn/inventor/tutorials/library/$tutorialSlug/$moduleSlug'
    | '/learn/inventor/tutorials/library/$tutorialSlug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/admin/inventor'
    | '/email/unsubscribe'
    | '/learn/inventor'
    | '/admin/articles/$slug'
    | '/admin/practice/$slug'
    | '/admin/practice/taxonomy'
    | '/admin/tutorials/$slug'
    | '/api/public/feedback'
    | '/learn/inventor/articles'
    | '/learn/inventor/part1'
    | '/learn/inventor/tutorials'
    | '/lovable/email/suppression'
    | '/admin/articles/'
    | '/admin/practice/'
    | '/admin/tutorials/'
    | '/learn/inventor/'
    | '/learn/inventor/articles/$slug'
    | '/learn/inventor/part1/$tabId'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/learn/inventor/articles/'
    | '/learn/inventor/part1/'
    | '/learn/inventor/tutorials/'
    | '/learn/inventor/part1/$tabId/$buttonId'
    | '/learn/inventor/tutorials/library/$tutorialSlug'
    | '/learn/inventor/tutorials/practice-problems/$slug'
    | '/learn/inventor/part1/$tabId/'
    | '/learn/inventor/tutorials/library/'
    | '/learn/inventor/tutorials/practice-problems/'
    | '/learn/inventor/tutorials/library/$tutorialSlug/$moduleSlug'
    | '/learn/inventor/tutorials/library/$tutorialSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AdminInventorRoute: typeof AdminInventorRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LearnInventorRoute: typeof LearnInventorRouteWithChildren
  AdminArticlesSlugRoute: typeof AdminArticlesSlugRoute
  AdminPracticeSlugRoute: typeof AdminPracticeSlugRoute
  AdminPracticeTaxonomyRoute: typeof AdminPracticeTaxonomyRoute
  AdminTutorialsSlugRoute: typeof AdminTutorialsSlugRoute
  ApiPublicFeedbackRoute: typeof ApiPublicFeedbackRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
  AdminPracticeIndexRoute: typeof AdminPracticeIndexRoute
  AdminTutorialsIndexRoute: typeof AdminTutorialsIndexRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/inventor': {
      id: '/learn/inventor'
      path: '/learn/inventor'
      fullPath: '/learn/inventor'
      preLoaderRoute: typeof LearnInventorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventor': {
      id: '/admin/inventor'
      path: '/admin/inventor'
      fullPath: '/admin/inventor'
      preLoaderRoute: typeof AdminInventorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/inventor/': {
      id: '/learn/inventor/'
      path: '/'
      fullPath: '/learn/inventor/'
      preLoaderRoute: typeof LearnInventorIndexRouteImport
      parentRoute: typeof LearnInventorRoute
    }
    '/admin/tutorials/': {
      id: '/admin/tutorials/'
      path: '/admin/tutorials'
      fullPath: '/admin/tutorials/'
      preLoaderRoute: typeof AdminTutorialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/practice/': {
      id: '/admin/practice/'
      path: '/admin/practice'
      fullPath: '/admin/practice/'
      preLoaderRoute: typeof AdminPracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/admin/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/inventor/tutorials': {
      id: '/learn/inventor/tutorials'
      path: '/tutorials'
      fullPath: '/learn/inventor/tutorials'
      preLoaderRoute: typeof LearnInventorTutorialsRouteImport
      parentRoute: typeof LearnInventorRoute
    }
    '/learn/inventor/part1': {
      id: '/learn/inventor/part1'
      path: '/part1'
      fullPath: '/learn/inventor/part1'
      preLoaderRoute: typeof LearnInventorPart1RouteImport
      parentRoute: typeof LearnInventorRoute
    }
    '/learn/inventor/articles': {
      id: '/learn/inventor/articles'
      path: '/articles'
      fullPath: '/learn/inventor/articles'
      preLoaderRoute: typeof LearnInventorArticlesRouteImport
      parentRoute: typeof LearnInventorRoute
    }
    '/api/public/feedback': {
      id: '/api/public/feedback'
      path: '/api/public/feedback'
      fullPath: '/api/public/feedback'
      preLoaderRoute: typeof ApiPublicFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tutorials/$slug': {
      id: '/admin/tutorials/$slug'
      path: '/admin/tutorials/$slug'
      fullPath: '/admin/tutorials/$slug'
      preLoaderRoute: typeof AdminTutorialsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/practice/taxonomy': {
      id: '/admin/practice/taxonomy'
      path: '/admin/practice/taxonomy'
      fullPath: '/admin/practice/taxonomy'
      preLoaderRoute: typeof AdminPracticeTaxonomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/practice/$slug': {
      id: '/admin/practice/$slug'
      path: '/admin/practice/$slug'
      fullPath: '/admin/practice/$slug'
      preLoaderRoute: typeof AdminPracticeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/$slug': {
      id: '/admin/articles/$slug'
      path: '/admin/articles/$slug'
      fullPath: '/admin/articles/$slug'
      preLoaderRoute: typeof AdminArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/inventor/tutorials/': {
      id: '/learn/inventor/tutorials/'
      path: '/'
      fullPath: '/learn/inventor/tutorials/'
      preLoaderRoute: typeof LearnInventorTutorialsIndexRouteImport
      parentRoute: typeof LearnInventorTutorialsRoute
    }
    '/learn/inventor/part1/': {
      id: '/learn/inventor/part1/'
      path: '/'
      fullPath: '/learn/inventor/part1/'
      preLoaderRoute: typeof LearnInventorPart1IndexRouteImport
      parentRoute: typeof LearnInventorPart1Route
    }
    '/learn/inventor/articles/': {
      id: '/learn/inventor/articles/'
      path: '/'
      fullPath: '/learn/inventor/articles/'
      preLoaderRoute: typeof LearnInventorArticlesIndexRouteImport
      parentRoute: typeof LearnInventorArticlesRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/inventor/part1/$tabId': {
      id: '/learn/inventor/part1/$tabId'
      path: '/$tabId'
      fullPath: '/learn/inventor/part1/$tabId'
      preLoaderRoute: typeof LearnInventorPart1TabIdRouteImport
      parentRoute: typeof LearnInventorPart1Route
    }
    '/learn/inventor/articles/$slug': {
      id: '/learn/inventor/articles/$slug'
      path: '/$slug'
      fullPath: '/learn/inventor/articles/$slug'
      preLoaderRoute: typeof LearnInventorArticlesSlugRouteImport
      parentRoute: typeof LearnInventorArticlesRoute
    }
    '/learn/inventor/tutorials/practice-problems/': {
      id: '/learn/inventor/tutorials/practice-problems/'
      path: '/practice-problems'
      fullPath: '/learn/inventor/tutorials/practice-problems/'
      preLoaderRoute: typeof LearnInventorTutorialsPracticeProblemsIndexRouteImport
      parentRoute: typeof LearnInventorTutorialsRoute
    }
    '/learn/inventor/tutorials/library/': {
      id: '/learn/inventor/tutorials/library/'
      path: '/library'
      fullPath: '/learn/inventor/tutorials/library/'
      preLoaderRoute: typeof LearnInventorTutorialsLibraryIndexRouteImport
      parentRoute: typeof LearnInventorTutorialsRoute
    }
    '/learn/inventor/part1/$tabId/': {
      id: '/learn/inventor/part1/$tabId/'
      path: '/'
      fullPath: '/learn/inventor/part1/$tabId/'
      preLoaderRoute: typeof LearnInventorPart1TabIdIndexRouteImport
      parentRoute: typeof LearnInventorPart1TabIdRoute
    }
    '/learn/inventor/tutorials/practice-problems/$slug': {
      id: '/learn/inventor/tutorials/practice-problems/$slug'
      path: '/practice-problems/$slug'
      fullPath: '/learn/inventor/tutorials/practice-problems/$slug'
      preLoaderRoute: typeof LearnInventorTutorialsPracticeProblemsSlugRouteImport
      parentRoute: typeof LearnInventorTutorialsRoute
    }
    '/learn/inventor/tutorials/library/$tutorialSlug': {
      id: '/learn/inventor/tutorials/library/$tutorialSlug'
      path: '/library/$tutorialSlug'
      fullPath: '/learn/inventor/tutorials/library/$tutorialSlug'
      preLoaderRoute: typeof LearnInventorTutorialsLibraryTutorialSlugRouteImport
      parentRoute: typeof LearnInventorTutorialsRoute
    }
    '/learn/inventor/part1/$tabId/$buttonId': {
      id: '/learn/inventor/part1/$tabId/$buttonId'
      path: '/$buttonId'
      fullPath: '/learn/inventor/part1/$tabId/$buttonId'
      preLoaderRoute: typeof LearnInventorPart1TabIdButtonIdRouteImport
      parentRoute: typeof LearnInventorPart1TabIdRoute
    }
    '/learn/inventor/tutorials/library/$tutorialSlug/': {
      id: '/learn/inventor/tutorials/library/$tutorialSlug/'
      path: '/'
      fullPath: '/learn/inventor/tutorials/library/$tutorialSlug/'
      preLoaderRoute: typeof LearnInventorTutorialsLibraryTutorialSlugIndexRouteImport
      parentRoute: typeof LearnInventorTutorialsLibraryTutorialSlugRoute
    }
    '/learn/inventor/tutorials/library/$tutorialSlug/$moduleSlug': {
      id: '/learn/inventor/tutorials/library/$tutorialSlug/$moduleSlug'
      path: '/$moduleSlug'
      fullPath: '/learn/inventor/tutorials/library/$tutorialSlug/$moduleSlug'
      preLoaderRoute: typeof LearnInventorTutorialsLibraryTutorialSlugModuleSlugRouteImport
      parentRoute: typeof LearnInventorTutorialsLibraryTutorialSlugRoute
    }
  }
}

interface LearnInventorArticlesRouteChildren {
  LearnInventorArticlesSlugRoute: typeof LearnInventorArticlesSlugRoute
  LearnInventorArticlesIndexRoute: typeof LearnInventorArticlesIndexRoute
}

const LearnInventorArticlesRouteChildren: LearnInventorArticlesRouteChildren = {
  LearnInventorArticlesSlugRoute: LearnInventorArticlesSlugRoute,
  LearnInventorArticlesIndexRoute: LearnInventorArticlesIndexRoute,
}

const LearnInventorArticlesRouteWithChildren =
  LearnInventorArticlesRoute._addFileChildren(
    LearnInventorArticlesRouteChildren,
  )

interface LearnInventorPart1TabIdRouteChildren {
  LearnInventorPart1TabIdButtonIdRoute: typeof LearnInventorPart1TabIdButtonIdRoute
  LearnInventorPart1TabIdIndexRoute: typeof LearnInventorPart1TabIdIndexRoute
}

const LearnInventorPart1TabIdRouteChildren: LearnInventorPart1TabIdRouteChildren =
  {
    LearnInventorPart1TabIdButtonIdRoute: LearnInventorPart1TabIdButtonIdRoute,
    LearnInventorPart1TabIdIndexRoute: LearnInventorPart1TabIdIndexRoute,
  }

const LearnInventorPart1TabIdRouteWithChildren =
  LearnInventorPart1TabIdRoute._addFileChildren(
    LearnInventorPart1TabIdRouteChildren,
  )

interface LearnInventorPart1RouteChildren {
  LearnInventorPart1TabIdRoute: typeof LearnInventorPart1TabIdRouteWithChildren
  LearnInventorPart1IndexRoute: typeof LearnInventorPart1IndexRoute
}

const LearnInventorPart1RouteChildren: LearnInventorPart1RouteChildren = {
  LearnInventorPart1TabIdRoute: LearnInventorPart1TabIdRouteWithChildren,
  LearnInventorPart1IndexRoute: LearnInventorPart1IndexRoute,
}

const LearnInventorPart1RouteWithChildren =
  LearnInventorPart1Route._addFileChildren(LearnInventorPart1RouteChildren)

interface LearnInventorTutorialsLibraryTutorialSlugRouteChildren {
  LearnInventorTutorialsLibraryTutorialSlugModuleSlugRoute: typeof LearnInventorTutorialsLibraryTutorialSlugModuleSlugRoute
  LearnInventorTutorialsLibraryTutorialSlugIndexRoute: typeof LearnInventorTutorialsLibraryTutorialSlugIndexRoute
}

const LearnInventorTutorialsLibraryTutorialSlugRouteChildren: LearnInventorTutorialsLibraryTutorialSlugRouteChildren =
  {
    LearnInventorTutorialsLibraryTutorialSlugModuleSlugRoute:
      LearnInventorTutorialsLibraryTutorialSlugModuleSlugRoute,
    LearnInventorTutorialsLibraryTutorialSlugIndexRoute:
      LearnInventorTutorialsLibraryTutorialSlugIndexRoute,
  }

const LearnInventorTutorialsLibraryTutorialSlugRouteWithChildren =
  LearnInventorTutorialsLibraryTutorialSlugRoute._addFileChildren(
    LearnInventorTutorialsLibraryTutorialSlugRouteChildren,
  )

interface LearnInventorTutorialsRouteChildren {
  LearnInventorTutorialsIndexRoute: typeof LearnInventorTutorialsIndexRoute
  LearnInventorTutorialsLibraryTutorialSlugRoute: typeof LearnInventorTutorialsLibraryTutorialSlugRouteWithChildren
  LearnInventorTutorialsPracticeProblemsSlugRoute: typeof LearnInventorTutorialsPracticeProblemsSlugRoute
  LearnInventorTutorialsLibraryIndexRoute: typeof LearnInventorTutorialsLibraryIndexRoute
  LearnInventorTutorialsPracticeProblemsIndexRoute: typeof LearnInventorTutorialsPracticeProblemsIndexRoute
}

const LearnInventorTutorialsRouteChildren: LearnInventorTutorialsRouteChildren =
  {
    LearnInventorTutorialsIndexRoute: LearnInventorTutorialsIndexRoute,
    LearnInventorTutorialsLibraryTutorialSlugRoute:
      LearnInventorTutorialsLibraryTutorialSlugRouteWithChildren,
    LearnInventorTutorialsPracticeProblemsSlugRoute:
      LearnInventorTutorialsPracticeProblemsSlugRoute,
    LearnInventorTutorialsLibraryIndexRoute:
      LearnInventorTutorialsLibraryIndexRoute,
    LearnInventorTutorialsPracticeProblemsIndexRoute:
      LearnInventorTutorialsPracticeProblemsIndexRoute,
  }

const LearnInventorTutorialsRouteWithChildren =
  LearnInventorTutorialsRoute._addFileChildren(
    LearnInventorTutorialsRouteChildren,
  )

interface LearnInventorRouteChildren {
  LearnInventorArticlesRoute: typeof LearnInventorArticlesRouteWithChildren
  LearnInventorPart1Route: typeof LearnInventorPart1RouteWithChildren
  LearnInventorTutorialsRoute: typeof LearnInventorTutorialsRouteWithChildren
  LearnInventorIndexRoute: typeof LearnInventorIndexRoute
}

const LearnInventorRouteChildren: LearnInventorRouteChildren = {
  LearnInventorArticlesRoute: LearnInventorArticlesRouteWithChildren,
  LearnInventorPart1Route: LearnInventorPart1RouteWithChildren,
  LearnInventorTutorialsRoute: LearnInventorTutorialsRouteWithChildren,
  LearnInventorIndexRoute: LearnInventorIndexRoute,
}

const LearnInventorRouteWithChildren = LearnInventorRoute._addFileChildren(
  LearnInventorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AdminInventorRoute: AdminInventorRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LearnInventorRoute: LearnInventorRouteWithChildren,
  AdminArticlesSlugRoute: AdminArticlesSlugRoute,
  AdminPracticeSlugRoute: AdminPracticeSlugRoute,
  AdminPracticeTaxonomyRoute: AdminPracticeTaxonomyRoute,
  AdminTutorialsSlugRoute: AdminTutorialsSlugRoute,
  ApiPublicFeedbackRoute: ApiPublicFeedbackRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
  AdminPracticeIndexRoute: AdminPracticeIndexRoute,
  AdminTutorialsIndexRoute: AdminTutorialsIndexRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
