/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnInventorRouteImport } from './routes/learn.inventor'
import { Route as AdminInventorRouteImport } from './routes/admin.inventor'
import { Route as LearnInventorIndexRouteImport } from './routes/learn.inventor.index'
import { Route as AdminTutorialsIndexRouteImport } from './routes/admin.tutorials.index'
import { Route as AdminPracticeIndexRouteImport } from './routes/admin.practice.index'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin.articles.index'
import { Route as LearnInventorPartRouteImport } from './routes/learn.inventor.part'
import { Route as LearnInventorLearnRouteImport } from './routes/learn.inventor.learn'
import { Route as LearnInventorArticlesRouteImport } from './routes/learn.inventor.articles'
import { Route as AdminTutorialsSlugRouteImport } from './routes/admin.tutorials.$slug'
import { Route as AdminPracticeTaxonomyRouteImport } from './routes/admin.practice.taxonomy'
import { Route as AdminPracticeSlugRouteImport } from './routes/admin.practice.$slug'
import { Route as AdminArticlesSlugRouteImport } from './routes/admin.articles.$slug'
import { Route as LearnInventorLearnIndexRouteImport } from './routes/learn.inventor.learn.index'
import { Route as LearnInventorArticlesIndexRouteImport } from './routes/learn.inventor.articles.index'
import { Route as LearnInventorLearnVideosRouteImport } from './routes/learn.inventor.learn.videos'
import { Route as LearnInventorLearnTutorialsRouteImport } from './routes/learn.inventor.learn.tutorials'
import { Route as LearnInventorLearnPracticeRouteImport } from './routes/learn.inventor.learn.practice'
import { Route as LearnInventorLearnFirstPartRouteImport } from './routes/learn.inventor.learn.first-part'
import { Route as LearnInventorArticlesSlugRouteImport } from './routes/learn.inventor.articles.$slug'
import { Route as LearnInventorLearnTutorialsIndexRouteImport } from './routes/learn.inventor.learn.tutorials.index'
import { Route as LearnInventorLearnPracticeIndexRouteImport } from './routes/learn.inventor.learn.practice.index'
import { Route as LearnInventorLearnTutorialsSlugRouteImport } from './routes/learn.inventor.learn.tutorials.$slug'
import { Route as LearnInventorLearnPracticeSlugRouteImport } from './routes/learn.inventor.learn.practice.$slug'
import { Route as LearnInventorLearnTutorialsSlugIndexRouteImport } from './routes/learn.inventor.learn.tutorials.$slug.index'
import { Route as LearnInventorLearnTutorialsSlugModuleSlugRouteImport } from './routes/learn.inventor.learn.tutorials.$slug.$moduleSlug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnInventorRoute = LearnInventorRouteImport.update({
  id: '/learn/inventor',
  path: '/learn/inventor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventorRoute = AdminInventorRouteImport.update({
  id: '/admin/inventor',
  path: '/admin/inventor',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnInventorIndexRoute = LearnInventorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnInventorRoute,
} as any)
const AdminTutorialsIndexRoute = AdminTutorialsIndexRouteImport.update({
  id: '/admin/tutorials/',
  path: '/admin/tutorials/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPracticeIndexRoute = AdminPracticeIndexRouteImport.update({
  id: '/admin/practice/',
  path: '/admin/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/admin/articles/',
  path: '/admin/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnInventorPartRoute = LearnInventorPartRouteImport.update({
  id: '/part',
  path: '/part',
  getParentRoute: () => LearnInventorRoute,
} as any)
const LearnInventorLearnRoute = LearnInventorLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => LearnInventorRoute,
} as any)
const LearnInventorArticlesRoute = LearnInventorArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => LearnInventorRoute,
} as any)
const AdminTutorialsSlugRoute = AdminTutorialsSlugRouteImport.update({
  id: '/admin/tutorials/$slug',
  path: '/admin/tutorials/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPracticeTaxonomyRoute = AdminPracticeTaxonomyRouteImport.update({
  id: '/admin/practice/taxonomy',
  path: '/admin/practice/taxonomy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPracticeSlugRoute = AdminPracticeSlugRouteImport.update({
  id: '/admin/practice/$slug',
  path: '/admin/practice/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesSlugRoute = AdminArticlesSlugRouteImport.update({
  id: '/admin/articles/$slug',
  path: '/admin/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnInventorLearnIndexRoute = LearnInventorLearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnInventorLearnRoute,
} as any)
const LearnInventorArticlesIndexRoute =
  LearnInventorArticlesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LearnInventorArticlesRoute,
  } as any)
const LearnInventorLearnVideosRoute =
  LearnInventorLearnVideosRouteImport.update({
    id: '/videos',
    path: '/videos',
    getParentRoute: () => LearnInventorLearnRoute,
  } as any)
const LearnInventorLearnTutorialsRoute =
  LearnInventorLearnTutorialsRouteImport.update({
    id: '/tutorials',
    path: '/tutorials',
    getParentRoute: () => LearnInventorLearnRoute,
  } as any)
const LearnInventorLearnPracticeRoute =
  LearnInventorLearnPracticeRouteImport.update({
    id: '/practice',
    path: '/practice',
    getParentRoute: () => LearnInventorLearnRoute,
  } as any)
const LearnInventorLearnFirstPartRoute =
  LearnInventorLearnFirstPartRouteImport.update({
    id: '/first-part',
    path: '/first-part',
    getParentRoute: () => LearnInventorLearnRoute,
  } as any)
const LearnInventorArticlesSlugRoute =
  LearnInventorArticlesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => LearnInventorArticlesRoute,
  } as any)
const LearnInventorLearnTutorialsIndexRoute =
  LearnInventorLearnTutorialsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LearnInventorLearnTutorialsRoute,
  } as any)
const LearnInventorLearnPracticeIndexRoute =
  LearnInventorLearnPracticeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LearnInventorLearnPracticeRoute,
  } as any)
const LearnInventorLearnTutorialsSlugRoute =
  LearnInventorLearnTutorialsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => LearnInventorLearnTutorialsRoute,
  } as any)
const LearnInventorLearnPracticeSlugRoute =
  LearnInventorLearnPracticeSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => LearnInventorLearnPracticeRoute,
  } as any)
const LearnInventorLearnTutorialsSlugIndexRoute =
  LearnInventorLearnTutorialsSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LearnInventorLearnTutorialsSlugRoute,
  } as any)
const LearnInventorLearnTutorialsSlugModuleSlugRoute =
  LearnInventorLearnTutorialsSlugModuleSlugRouteImport.update({
    id: '/$moduleSlug',
    path: '/$moduleSlug',
    getParentRoute: () => LearnInventorLearnTutorialsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/inventor': typeof AdminInventorRoute
  '/learn/inventor': typeof LearnInventorRouteWithChildren
  '/admin/articles/$slug': typeof AdminArticlesSlugRoute
  '/admin/practice/$slug': typeof AdminPracticeSlugRoute
  '/admin/practice/taxonomy': typeof AdminPracticeTaxonomyRoute
  '/admin/tutorials/$slug': typeof AdminTutorialsSlugRoute
  '/learn/inventor/articles': typeof LearnInventorArticlesRouteWithChildren
  '/learn/inventor/learn': typeof LearnInventorLearnRouteWithChildren
  '/learn/inventor/part': typeof LearnInventorPartRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/practice/': typeof AdminPracticeIndexRoute
  '/admin/tutorials/': typeof AdminTutorialsIndexRoute
  '/learn/inventor/': typeof LearnInventorIndexRoute
  '/learn/inventor/articles/$slug': typeof LearnInventorArticlesSlugRoute
  '/learn/inventor/learn/first-part': typeof LearnInventorLearnFirstPartRoute
  '/learn/inventor/learn/practice': typeof LearnInventorLearnPracticeRouteWithChildren
  '/learn/inventor/learn/tutorials': typeof LearnInventorLearnTutorialsRouteWithChildren
  '/learn/inventor/learn/videos': typeof LearnInventorLearnVideosRoute
  '/learn/inventor/articles/': typeof LearnInventorArticlesIndexRoute
  '/learn/inventor/learn/': typeof LearnInventorLearnIndexRoute
  '/learn/inventor/learn/practice/$slug': typeof LearnInventorLearnPracticeSlugRoute
  '/learn/inventor/learn/tutorials/$slug': typeof LearnInventorLearnTutorialsSlugRouteWithChildren
  '/learn/inventor/learn/practice/': typeof LearnInventorLearnPracticeIndexRoute
  '/learn/inventor/learn/tutorials/': typeof LearnInventorLearnTutorialsIndexRoute
  '/learn/inventor/learn/tutorials/$slug/$moduleSlug': typeof LearnInventorLearnTutorialsSlugModuleSlugRoute
  '/learn/inventor/learn/tutorials/$slug/': typeof LearnInventorLearnTutorialsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/inventor': typeof AdminInventorRoute
  '/admin/articles/$slug': typeof AdminArticlesSlugRoute
  '/admin/practice/$slug': typeof AdminPracticeSlugRoute
  '/admin/practice/taxonomy': typeof AdminPracticeTaxonomyRoute
  '/admin/tutorials/$slug': typeof AdminTutorialsSlugRoute
  '/learn/inventor/part': typeof LearnInventorPartRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
  '/admin/practice': typeof AdminPracticeIndexRoute
  '/admin/tutorials': typeof AdminTutorialsIndexRoute
  '/learn/inventor': typeof LearnInventorIndexRoute
  '/learn/inventor/articles/$slug': typeof LearnInventorArticlesSlugRoute
  '/learn/inventor/learn/first-part': typeof LearnInventorLearnFirstPartRoute
  '/learn/inventor/learn/videos': typeof LearnInventorLearnVideosRoute
  '/learn/inventor/articles': typeof LearnInventorArticlesIndexRoute
  '/learn/inventor/learn': typeof LearnInventorLearnIndexRoute
  '/learn/inventor/learn/practice/$slug': typeof LearnInventorLearnPracticeSlugRoute
  '/learn/inventor/learn/practice': typeof LearnInventorLearnPracticeIndexRoute
  '/learn/inventor/learn/tutorials': typeof LearnInventorLearnTutorialsIndexRoute
  '/learn/inventor/learn/tutorials/$slug/$moduleSlug': typeof LearnInventorLearnTutorialsSlugModuleSlugRoute
  '/learn/inventor/learn/tutorials/$slug': typeof LearnInventorLearnTutorialsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/inventor': typeof AdminInventorRoute
  '/learn/inventor': typeof LearnInventorRouteWithChildren
  '/admin/articles/$slug': typeof AdminArticlesSlugRoute
  '/admin/practice/$slug': typeof AdminPracticeSlugRoute
  '/admin/practice/taxonomy': typeof AdminPracticeTaxonomyRoute
  '/admin/tutorials/$slug': typeof AdminTutorialsSlugRoute
  '/learn/inventor/articles': typeof LearnInventorArticlesRouteWithChildren
  '/learn/inventor/learn': typeof LearnInventorLearnRouteWithChildren
  '/learn/inventor/part': typeof LearnInventorPartRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/practice/': typeof AdminPracticeIndexRoute
  '/admin/tutorials/': typeof AdminTutorialsIndexRoute
  '/learn/inventor/': typeof LearnInventorIndexRoute
  '/learn/inventor/articles/$slug': typeof LearnInventorArticlesSlugRoute
  '/learn/inventor/learn/first-part': typeof LearnInventorLearnFirstPartRoute
  '/learn/inventor/learn/practice': typeof LearnInventorLearnPracticeRouteWithChildren
  '/learn/inventor/learn/tutorials': typeof LearnInventorLearnTutorialsRouteWithChildren
  '/learn/inventor/learn/videos': typeof LearnInventorLearnVideosRoute
  '/learn/inventor/articles/': typeof LearnInventorArticlesIndexRoute
  '/learn/inventor/learn/': typeof LearnInventorLearnIndexRoute
  '/learn/inventor/learn/practice/$slug': typeof LearnInventorLearnPracticeSlugRoute
  '/learn/inventor/learn/tutorials/$slug': typeof LearnInventorLearnTutorialsSlugRouteWithChildren
  '/learn/inventor/learn/practice/': typeof LearnInventorLearnPracticeIndexRoute
  '/learn/inventor/learn/tutorials/': typeof LearnInventorLearnTutorialsIndexRoute
  '/learn/inventor/learn/tutorials/$slug/$moduleSlug': typeof LearnInventorLearnTutorialsSlugModuleSlugRoute
  '/learn/inventor/learn/tutorials/$slug/': typeof LearnInventorLearnTutorialsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/inventor'
    | '/learn/inventor'
    | '/admin/articles/$slug'
    | '/admin/practice/$slug'
    | '/admin/practice/taxonomy'
    | '/admin/tutorials/$slug'
    | '/learn/inventor/articles'
    | '/learn/inventor/learn'
    | '/learn/inventor/part'
    | '/admin/articles/'
    | '/admin/practice/'
    | '/admin/tutorials/'
    | '/learn/inventor/'
    | '/learn/inventor/articles/$slug'
    | '/learn/inventor/learn/first-part'
    | '/learn/inventor/learn/practice'
    | '/learn/inventor/learn/tutorials'
    | '/learn/inventor/learn/videos'
    | '/learn/inventor/articles/'
    | '/learn/inventor/learn/'
    | '/learn/inventor/learn/practice/$slug'
    | '/learn/inventor/learn/tutorials/$slug'
    | '/learn/inventor/learn/practice/'
    | '/learn/inventor/learn/tutorials/'
    | '/learn/inventor/learn/tutorials/$slug/$moduleSlug'
    | '/learn/inventor/learn/tutorials/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/inventor'
    | '/admin/articles/$slug'
    | '/admin/practice/$slug'
    | '/admin/practice/taxonomy'
    | '/admin/tutorials/$slug'
    | '/learn/inventor/part'
    | '/admin/articles'
    | '/admin/practice'
    | '/admin/tutorials'
    | '/learn/inventor'
    | '/learn/inventor/articles/$slug'
    | '/learn/inventor/learn/first-part'
    | '/learn/inventor/learn/videos'
    | '/learn/inventor/articles'
    | '/learn/inventor/learn'
    | '/learn/inventor/learn/practice/$slug'
    | '/learn/inventor/learn/practice'
    | '/learn/inventor/learn/tutorials'
    | '/learn/inventor/learn/tutorials/$slug/$moduleSlug'
    | '/learn/inventor/learn/tutorials/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/admin/inventor'
    | '/learn/inventor'
    | '/admin/articles/$slug'
    | '/admin/practice/$slug'
    | '/admin/practice/taxonomy'
    | '/admin/tutorials/$slug'
    | '/learn/inventor/articles'
    | '/learn/inventor/learn'
    | '/learn/inventor/part'
    | '/admin/articles/'
    | '/admin/practice/'
    | '/admin/tutorials/'
    | '/learn/inventor/'
    | '/learn/inventor/articles/$slug'
    | '/learn/inventor/learn/first-part'
    | '/learn/inventor/learn/practice'
    | '/learn/inventor/learn/tutorials'
    | '/learn/inventor/learn/videos'
    | '/learn/inventor/articles/'
    | '/learn/inventor/learn/'
    | '/learn/inventor/learn/practice/$slug'
    | '/learn/inventor/learn/tutorials/$slug'
    | '/learn/inventor/learn/practice/'
    | '/learn/inventor/learn/tutorials/'
    | '/learn/inventor/learn/tutorials/$slug/$moduleSlug'
    | '/learn/inventor/learn/tutorials/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AdminInventorRoute: typeof AdminInventorRoute
  LearnInventorRoute: typeof LearnInventorRouteWithChildren
  AdminArticlesSlugRoute: typeof AdminArticlesSlugRoute
  AdminPracticeSlugRoute: typeof AdminPracticeSlugRoute
  AdminPracticeTaxonomyRoute: typeof AdminPracticeTaxonomyRoute
  AdminTutorialsSlugRoute: typeof AdminTutorialsSlugRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
  AdminPracticeIndexRoute: typeof AdminPracticeIndexRoute
  AdminTutorialsIndexRoute: typeof AdminTutorialsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/inventor': {
      id: '/learn/inventor'
      path: '/learn/inventor'
      fullPath: '/learn/inventor'
      preLoaderRoute: typeof LearnInventorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventor': {
      id: '/admin/inventor'
      path: '/admin/inventor'
      fullPath: '/admin/inventor'
      preLoaderRoute: typeof AdminInventorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/inventor/': {
      id: '/learn/inventor/'
      path: '/'
      fullPath: '/learn/inventor/'
      preLoaderRoute: typeof LearnInventorIndexRouteImport
      parentRoute: typeof LearnInventorRoute
    }
    '/admin/tutorials/': {
      id: '/admin/tutorials/'
      path: '/admin/tutorials'
      fullPath: '/admin/tutorials/'
      preLoaderRoute: typeof AdminTutorialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/practice/': {
      id: '/admin/practice/'
      path: '/admin/practice'
      fullPath: '/admin/practice/'
      preLoaderRoute: typeof AdminPracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/admin/articles'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/inventor/part': {
      id: '/learn/inventor/part'
      path: '/part'
      fullPath: '/learn/inventor/part'
      preLoaderRoute: typeof LearnInventorPartRouteImport
      parentRoute: typeof LearnInventorRoute
    }
    '/learn/inventor/learn': {
      id: '/learn/inventor/learn'
      path: '/learn'
      fullPath: '/learn/inventor/learn'
      preLoaderRoute: typeof LearnInventorLearnRouteImport
      parentRoute: typeof LearnInventorRoute
    }
    '/learn/inventor/articles': {
      id: '/learn/inventor/articles'
      path: '/articles'
      fullPath: '/learn/inventor/articles'
      preLoaderRoute: typeof LearnInventorArticlesRouteImport
      parentRoute: typeof LearnInventorRoute
    }
    '/admin/tutorials/$slug': {
      id: '/admin/tutorials/$slug'
      path: '/admin/tutorials/$slug'
      fullPath: '/admin/tutorials/$slug'
      preLoaderRoute: typeof AdminTutorialsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/practice/taxonomy': {
      id: '/admin/practice/taxonomy'
      path: '/admin/practice/taxonomy'
      fullPath: '/admin/practice/taxonomy'
      preLoaderRoute: typeof AdminPracticeTaxonomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/practice/$slug': {
      id: '/admin/practice/$slug'
      path: '/admin/practice/$slug'
      fullPath: '/admin/practice/$slug'
      preLoaderRoute: typeof AdminPracticeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/$slug': {
      id: '/admin/articles/$slug'
      path: '/admin/articles/$slug'
      fullPath: '/admin/articles/$slug'
      preLoaderRoute: typeof AdminArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/inventor/learn/': {
      id: '/learn/inventor/learn/'
      path: '/'
      fullPath: '/learn/inventor/learn/'
      preLoaderRoute: typeof LearnInventorLearnIndexRouteImport
      parentRoute: typeof LearnInventorLearnRoute
    }
    '/learn/inventor/articles/': {
      id: '/learn/inventor/articles/'
      path: '/'
      fullPath: '/learn/inventor/articles/'
      preLoaderRoute: typeof LearnInventorArticlesIndexRouteImport
      parentRoute: typeof LearnInventorArticlesRoute
    }
    '/learn/inventor/learn/videos': {
      id: '/learn/inventor/learn/videos'
      path: '/videos'
      fullPath: '/learn/inventor/learn/videos'
      preLoaderRoute: typeof LearnInventorLearnVideosRouteImport
      parentRoute: typeof LearnInventorLearnRoute
    }
    '/learn/inventor/learn/tutorials': {
      id: '/learn/inventor/learn/tutorials'
      path: '/tutorials'
      fullPath: '/learn/inventor/learn/tutorials'
      preLoaderRoute: typeof LearnInventorLearnTutorialsRouteImport
      parentRoute: typeof LearnInventorLearnRoute
    }
    '/learn/inventor/learn/practice': {
      id: '/learn/inventor/learn/practice'
      path: '/practice'
      fullPath: '/learn/inventor/learn/practice'
      preLoaderRoute: typeof LearnInventorLearnPracticeRouteImport
      parentRoute: typeof LearnInventorLearnRoute
    }
    '/learn/inventor/learn/first-part': {
      id: '/learn/inventor/learn/first-part'
      path: '/first-part'
      fullPath: '/learn/inventor/learn/first-part'
      preLoaderRoute: typeof LearnInventorLearnFirstPartRouteImport
      parentRoute: typeof LearnInventorLearnRoute
    }
    '/learn/inventor/articles/$slug': {
      id: '/learn/inventor/articles/$slug'
      path: '/$slug'
      fullPath: '/learn/inventor/articles/$slug'
      preLoaderRoute: typeof LearnInventorArticlesSlugRouteImport
      parentRoute: typeof LearnInventorArticlesRoute
    }
    '/learn/inventor/learn/tutorials/': {
      id: '/learn/inventor/learn/tutorials/'
      path: '/'
      fullPath: '/learn/inventor/learn/tutorials/'
      preLoaderRoute: typeof LearnInventorLearnTutorialsIndexRouteImport
      parentRoute: typeof LearnInventorLearnTutorialsRoute
    }
    '/learn/inventor/learn/practice/': {
      id: '/learn/inventor/learn/practice/'
      path: '/'
      fullPath: '/learn/inventor/learn/practice/'
      preLoaderRoute: typeof LearnInventorLearnPracticeIndexRouteImport
      parentRoute: typeof LearnInventorLearnPracticeRoute
    }
    '/learn/inventor/learn/tutorials/$slug': {
      id: '/learn/inventor/learn/tutorials/$slug'
      path: '/$slug'
      fullPath: '/learn/inventor/learn/tutorials/$slug'
      preLoaderRoute: typeof LearnInventorLearnTutorialsSlugRouteImport
      parentRoute: typeof LearnInventorLearnTutorialsRoute
    }
    '/learn/inventor/learn/practice/$slug': {
      id: '/learn/inventor/learn/practice/$slug'
      path: '/$slug'
      fullPath: '/learn/inventor/learn/practice/$slug'
      preLoaderRoute: typeof LearnInventorLearnPracticeSlugRouteImport
      parentRoute: typeof LearnInventorLearnPracticeRoute
    }
    '/learn/inventor/learn/tutorials/$slug/': {
      id: '/learn/inventor/learn/tutorials/$slug/'
      path: '/'
      fullPath: '/learn/inventor/learn/tutorials/$slug/'
      preLoaderRoute: typeof LearnInventorLearnTutorialsSlugIndexRouteImport
      parentRoute: typeof LearnInventorLearnTutorialsSlugRoute
    }
    '/learn/inventor/learn/tutorials/$slug/$moduleSlug': {
      id: '/learn/inventor/learn/tutorials/$slug/$moduleSlug'
      path: '/$moduleSlug'
      fullPath: '/learn/inventor/learn/tutorials/$slug/$moduleSlug'
      preLoaderRoute: typeof LearnInventorLearnTutorialsSlugModuleSlugRouteImport
      parentRoute: typeof LearnInventorLearnTutorialsSlugRoute
    }
  }
}

interface LearnInventorArticlesRouteChildren {
  LearnInventorArticlesSlugRoute: typeof LearnInventorArticlesSlugRoute
  LearnInventorArticlesIndexRoute: typeof LearnInventorArticlesIndexRoute
}

const LearnInventorArticlesRouteChildren: LearnInventorArticlesRouteChildren = {
  LearnInventorArticlesSlugRoute: LearnInventorArticlesSlugRoute,
  LearnInventorArticlesIndexRoute: LearnInventorArticlesIndexRoute,
}

const LearnInventorArticlesRouteWithChildren =
  LearnInventorArticlesRoute._addFileChildren(
    LearnInventorArticlesRouteChildren,
  )

interface LearnInventorLearnPracticeRouteChildren {
  LearnInventorLearnPracticeSlugRoute: typeof LearnInventorLearnPracticeSlugRoute
  LearnInventorLearnPracticeIndexRoute: typeof LearnInventorLearnPracticeIndexRoute
}

const LearnInventorLearnPracticeRouteChildren: LearnInventorLearnPracticeRouteChildren =
  {
    LearnInventorLearnPracticeSlugRoute: LearnInventorLearnPracticeSlugRoute,
    LearnInventorLearnPracticeIndexRoute: LearnInventorLearnPracticeIndexRoute,
  }

const LearnInventorLearnPracticeRouteWithChildren =
  LearnInventorLearnPracticeRoute._addFileChildren(
    LearnInventorLearnPracticeRouteChildren,
  )

interface LearnInventorLearnTutorialsSlugRouteChildren {
  LearnInventorLearnTutorialsSlugModuleSlugRoute: typeof LearnInventorLearnTutorialsSlugModuleSlugRoute
  LearnInventorLearnTutorialsSlugIndexRoute: typeof LearnInventorLearnTutorialsSlugIndexRoute
}

const LearnInventorLearnTutorialsSlugRouteChildren: LearnInventorLearnTutorialsSlugRouteChildren =
  {
    LearnInventorLearnTutorialsSlugModuleSlugRoute:
      LearnInventorLearnTutorialsSlugModuleSlugRoute,
    LearnInventorLearnTutorialsSlugIndexRoute:
      LearnInventorLearnTutorialsSlugIndexRoute,
  }

const LearnInventorLearnTutorialsSlugRouteWithChildren =
  LearnInventorLearnTutorialsSlugRoute._addFileChildren(
    LearnInventorLearnTutorialsSlugRouteChildren,
  )

interface LearnInventorLearnTutorialsRouteChildren {
  LearnInventorLearnTutorialsSlugRoute: typeof LearnInventorLearnTutorialsSlugRouteWithChildren
  LearnInventorLearnTutorialsIndexRoute: typeof LearnInventorLearnTutorialsIndexRoute
}

const LearnInventorLearnTutorialsRouteChildren: LearnInventorLearnTutorialsRouteChildren =
  {
    LearnInventorLearnTutorialsSlugRoute:
      LearnInventorLearnTutorialsSlugRouteWithChildren,
    LearnInventorLearnTutorialsIndexRoute:
      LearnInventorLearnTutorialsIndexRoute,
  }

const LearnInventorLearnTutorialsRouteWithChildren =
  LearnInventorLearnTutorialsRoute._addFileChildren(
    LearnInventorLearnTutorialsRouteChildren,
  )

interface LearnInventorLearnRouteChildren {
  LearnInventorLearnFirstPartRoute: typeof LearnInventorLearnFirstPartRoute
  LearnInventorLearnPracticeRoute: typeof LearnInventorLearnPracticeRouteWithChildren
  LearnInventorLearnTutorialsRoute: typeof LearnInventorLearnTutorialsRouteWithChildren
  LearnInventorLearnVideosRoute: typeof LearnInventorLearnVideosRoute
  LearnInventorLearnIndexRoute: typeof LearnInventorLearnIndexRoute
}

const LearnInventorLearnRouteChildren: LearnInventorLearnRouteChildren = {
  LearnInventorLearnFirstPartRoute: LearnInventorLearnFirstPartRoute,
  LearnInventorLearnPracticeRoute: LearnInventorLearnPracticeRouteWithChildren,
  LearnInventorLearnTutorialsRoute:
    LearnInventorLearnTutorialsRouteWithChildren,
  LearnInventorLearnVideosRoute: LearnInventorLearnVideosRoute,
  LearnInventorLearnIndexRoute: LearnInventorLearnIndexRoute,
}

const LearnInventorLearnRouteWithChildren =
  LearnInventorLearnRoute._addFileChildren(LearnInventorLearnRouteChildren)

interface LearnInventorRouteChildren {
  LearnInventorArticlesRoute: typeof LearnInventorArticlesRouteWithChildren
  LearnInventorLearnRoute: typeof LearnInventorLearnRouteWithChildren
  LearnInventorPartRoute: typeof LearnInventorPartRoute
  LearnInventorIndexRoute: typeof LearnInventorIndexRoute
}

const LearnInventorRouteChildren: LearnInventorRouteChildren = {
  LearnInventorArticlesRoute: LearnInventorArticlesRouteWithChildren,
  LearnInventorLearnRoute: LearnInventorLearnRouteWithChildren,
  LearnInventorPartRoute: LearnInventorPartRoute,
  LearnInventorIndexRoute: LearnInventorIndexRoute,
}

const LearnInventorRouteWithChildren = LearnInventorRoute._addFileChildren(
  LearnInventorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AdminInventorRoute: AdminInventorRoute,
  LearnInventorRoute: LearnInventorRouteWithChildren,
  AdminArticlesSlugRoute: AdminArticlesSlugRoute,
  AdminPracticeSlugRoute: AdminPracticeSlugRoute,
  AdminPracticeTaxonomyRoute: AdminPracticeTaxonomyRoute,
  AdminTutorialsSlugRoute: AdminTutorialsSlugRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
  AdminPracticeIndexRoute: AdminPracticeIndexRoute,
  AdminTutorialsIndexRoute: AdminTutorialsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
