/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnInventorRouteImport } from './routes/learn.inventor'
import { Route as AdminInventorRouteImport } from './routes/admin.inventor'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as AdminArticlesSlugRouteImport } from './routes/admin.articles.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnInventorRoute = LearnInventorRouteImport.update({
  id: '/learn/inventor',
  path: '/learn/inventor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventorRoute = AdminInventorRouteImport.update({
  id: '/admin/inventor',
  path: '/admin/inventor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/admin/articles',
  path: '/admin/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArticlesSlugRoute = AdminArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AdminArticlesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/inventor': typeof AdminInventorRoute
  '/learn/inventor': typeof LearnInventorRoute
  '/admin/articles/$slug': typeof AdminArticlesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/inventor': typeof AdminInventorRoute
  '/learn/inventor': typeof LearnInventorRoute
  '/admin/articles/$slug': typeof AdminArticlesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/inventor': typeof AdminInventorRoute
  '/learn/inventor': typeof LearnInventorRoute
  '/admin/articles/$slug': typeof AdminArticlesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/articles'
    | '/admin/inventor'
    | '/learn/inventor'
    | '/admin/articles/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/articles'
    | '/admin/inventor'
    | '/learn/inventor'
    | '/admin/articles/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/admin/articles'
    | '/admin/inventor'
    | '/learn/inventor'
    | '/admin/articles/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AdminArticlesRoute: typeof AdminArticlesRouteWithChildren
  AdminInventorRoute: typeof AdminInventorRoute
  LearnInventorRoute: typeof LearnInventorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/inventor': {
      id: '/learn/inventor'
      path: '/learn/inventor'
      fullPath: '/learn/inventor'
      preLoaderRoute: typeof LearnInventorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/inventor': {
      id: '/admin/inventor'
      path: '/admin/inventor'
      fullPath: '/admin/inventor'
      preLoaderRoute: typeof AdminInventorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/admin/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/articles/$slug': {
      id: '/admin/articles/$slug'
      path: '/$slug'
      fullPath: '/admin/articles/$slug'
      preLoaderRoute: typeof AdminArticlesSlugRouteImport
      parentRoute: typeof AdminArticlesRoute
    }
  }
}

interface AdminArticlesRouteChildren {
  AdminArticlesSlugRoute: typeof AdminArticlesSlugRoute
}

const AdminArticlesRouteChildren: AdminArticlesRouteChildren = {
  AdminArticlesSlugRoute: AdminArticlesSlugRoute,
}

const AdminArticlesRouteWithChildren = AdminArticlesRoute._addFileChildren(
  AdminArticlesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AdminArticlesRoute: AdminArticlesRouteWithChildren,
  AdminInventorRoute: AdminInventorRoute,
  LearnInventorRoute: LearnInventorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
